<?php

namespace Container2Vx6yxp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0BqFzZpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0BqFzZp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0BqFzZp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\IngredientsRepository', 'getIngredientsRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\IngredientsRepository',
        ]);
    }
}
