<?php

namespace Container2Vx6yxp;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CoG0kLaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CoG0kLa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CoG0kLa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recipes' => ['privates', '.errored..service_locator.CoG0kLa.App\\Entity\\Recipes', NULL, 'Cannot autowire service ".service_locator.CoG0kLa": it references class "App\\Entity\\Recipes" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'recipes' => 'App\\Entity\\Recipes',
        ]);
    }
}
