<?php

namespace ContainerBg2YjCx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecipesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CoG0kLa.App\Entity\Recipes' shared service.
     *
     * @return \App\Entity\Recipes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.CoG0kLa": it references class "App\\Entity\\Recipes" but no such service exists.');
    }
}
