<?php

namespace ContainerULGMgv3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kh6LozE.App\Entity\Comments' shared service.
     *
     * @return \App\Entity\Comments
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kh6LozE": it references class "App\\Entity\\Comments" but no such service exists.');
    }
}
