<?php

namespace ContainerChgkRML;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WwoHeylService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WwoHeyl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WwoHeyl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recipes' => ['privates', '.errored..service_locator.WwoHeyl.App\\Entity\\Recipes', NULL, 'Cannot autowire service ".service_locator.WwoHeyl": it references class "App\\Entity\\Recipes" but no such service exists.'],
        ], [
            'recipes' => 'App\\Entity\\Recipes',
        ]);
    }
}
