<?php

namespace ContainerTTMCwWW;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TsjDZN4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tsjDZN4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tsjDZN4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repository' => ['privates', 'App\\Repository\\RecipesRepository', 'getRecipesRepositoryService', true],
            'repositoryC' => ['privates', 'App\\Repository\\CategoriesRepository', 'getCategoriesRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\RecipesRepository',
            'repositoryC' => 'App\\Repository\\CategoriesRepository',
        ]);
    }
}
