<?php

namespace Container6YyNZQx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K6zuV1DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k6zuV1D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k6zuV1D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminCommentsController::comments' => ['privates', '.service_locator.CN8_8d2', 'get_ServiceLocator_CN88d2Service', true],
            'App\\Controller\\AdminCommentsController::modification' => ['privates', '.service_locator.t5jNp8S', 'get_ServiceLocator_T5jNp8SService', true],
            'App\\Controller\\AdminCommentsController::suppression' => ['privates', '.service_locator.kh6LozE', 'get_ServiceLocator_Kh6LozEService', true],
            'App\\Controller\\AdminRecipesController::modification' => ['privates', '.service_locator.Vh0Xgqt', 'get_ServiceLocator_Vh0XgqtService', true],
            'App\\Controller\\AdminRecipesController::recipes' => ['privates', '.service_locator.PyIw17T', 'get_ServiceLocator_PyIw17TService', true],
            'App\\Controller\\AdminRecipesController::suppression' => ['privates', '.service_locator.CoG0kLa', 'get_ServiceLocator_CoG0kLaService', true],
            'App\\Controller\\AdminSecuController::inscription' => ['privates', '.service_locator..tt6s91', 'get_ServiceLocator__Tt6s91Service', true],
            'App\\Controller\\AdminSecuController::login' => ['privates', '.service_locator.d2me_LS', 'get_ServiceLocator_D2meLSService', true],
            'App\\Controller\\IngredientsController::recipes' => ['privates', '.service_locator.0BqFzZp', 'get_ServiceLocator_0BqFzZpService', true],
            'App\\Controller\\RecipesController::recipes' => ['privates', '.service_locator.PyIw17T', 'get_ServiceLocator_PyIw17TService', true],
            'App\\Controller\\UsersController::changePassword' => ['privates', '.service_locator.gPh6X_L', 'get_ServiceLocator_GPh6XLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AdminCommentsController:comments' => ['privates', '.service_locator.CN8_8d2', 'get_ServiceLocator_CN88d2Service', true],
            'App\\Controller\\AdminCommentsController:modification' => ['privates', '.service_locator.t5jNp8S', 'get_ServiceLocator_T5jNp8SService', true],
            'App\\Controller\\AdminCommentsController:suppression' => ['privates', '.service_locator.kh6LozE', 'get_ServiceLocator_Kh6LozEService', true],
            'App\\Controller\\AdminRecipesController:modification' => ['privates', '.service_locator.Vh0Xgqt', 'get_ServiceLocator_Vh0XgqtService', true],
            'App\\Controller\\AdminRecipesController:recipes' => ['privates', '.service_locator.PyIw17T', 'get_ServiceLocator_PyIw17TService', true],
            'App\\Controller\\AdminRecipesController:suppression' => ['privates', '.service_locator.CoG0kLa', 'get_ServiceLocator_CoG0kLaService', true],
            'App\\Controller\\AdminSecuController:inscription' => ['privates', '.service_locator..tt6s91', 'get_ServiceLocator__Tt6s91Service', true],
            'App\\Controller\\AdminSecuController:login' => ['privates', '.service_locator.d2me_LS', 'get_ServiceLocator_D2meLSService', true],
            'App\\Controller\\IngredientsController:recipes' => ['privates', '.service_locator.0BqFzZp', 'get_ServiceLocator_0BqFzZpService', true],
            'App\\Controller\\RecipesController:recipes' => ['privates', '.service_locator.PyIw17T', 'get_ServiceLocator_PyIw17TService', true],
            'App\\Controller\\UsersController:changePassword' => ['privates', '.service_locator.gPh6X_L', 'get_ServiceLocator_GPh6XLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AdminCommentsController::comments' => '?',
            'App\\Controller\\AdminCommentsController::modification' => '?',
            'App\\Controller\\AdminCommentsController::suppression' => '?',
            'App\\Controller\\AdminRecipesController::modification' => '?',
            'App\\Controller\\AdminRecipesController::recipes' => '?',
            'App\\Controller\\AdminRecipesController::suppression' => '?',
            'App\\Controller\\AdminSecuController::inscription' => '?',
            'App\\Controller\\AdminSecuController::login' => '?',
            'App\\Controller\\IngredientsController::recipes' => '?',
            'App\\Controller\\RecipesController::recipes' => '?',
            'App\\Controller\\UsersController::changePassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminCommentsController:comments' => '?',
            'App\\Controller\\AdminCommentsController:modification' => '?',
            'App\\Controller\\AdminCommentsController:suppression' => '?',
            'App\\Controller\\AdminRecipesController:modification' => '?',
            'App\\Controller\\AdminRecipesController:recipes' => '?',
            'App\\Controller\\AdminRecipesController:suppression' => '?',
            'App\\Controller\\AdminSecuController:inscription' => '?',
            'App\\Controller\\AdminSecuController:login' => '?',
            'App\\Controller\\IngredientsController:recipes' => '?',
            'App\\Controller\\RecipesController:recipes' => '?',
            'App\\Controller\\UsersController:changePassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
