<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9JvhdaG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9JvhdaG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9JvhdaG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9JvhdaG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9JvhdaG\App_KernelDevDebugContainer([
    'container.build_hash' => '9JvhdaG',
    'container.build_id' => '2e2a1f9e',
    'container.build_time' => 1615564786,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9JvhdaG');
