<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerXGrDHww\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXGrDHww/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXGrDHww.legacy');
=======
if (\class_exists(\ContainerH7gyQjv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH7gyQjv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH7gyQjv.legacy');
>>>>>>> 2f08515ab6c14f2a5000bf2ee54820b42f638b08

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerXGrDHww\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXGrDHww\App_KernelDevDebugContainer([
    'container.build_hash' => 'XGrDHww',
    'container.build_id' => '5fa65414',
    'container.build_time' => 1616365672,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXGrDHww');
=======
    \class_alias(\ContainerH7gyQjv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH7gyQjv\App_KernelDevDebugContainer([
    'container.build_hash' => 'H7gyQjv',
    'container.build_id' => '6832677f',
    'container.build_time' => 1616341176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH7gyQjv');
>>>>>>> 2f08515ab6c14f2a5000bf2ee54820b42f638b08
