<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Vx6yxp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Vx6yxp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Vx6yxp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Vx6yxp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Vx6yxp\App_KernelDevDebugContainer([
    'container.build_hash' => '2Vx6yxp',
    'container.build_id' => 'b0270a2d',
    'container.build_time' => 1615411330,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Vx6yxp');
